# Generated by Django 5.2 on 2025-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('sms', 'ارسال کد via SMS'), ('totp', 'برنامه احراز هویت (Google Authenticator)'), ('none', 'غیرفعال')], default='none', max_length=10),
        ),
    ]
