# Generated by Django 5.2 on 2025-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounting', '0002_user_phone_number_user_two_factor_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
